"""sync_models_schema_drift

Revision ID: 27482216f0e8
Revises: 6499c4edd4d2
Create Date: 2026-07-05 11:20:02.296708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27482216f0e8'
down_revision: Union[str, None] = '6499c4edd4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('cart_items', sa.Column('color_hex', sa.String(length=7), nullable=True))
    op.add_column('cart_items', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('order_items', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('order_items', sa.Column('color_hex', sa.String(length=7), nullable=True))
    op.add_column('order_items', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('subtotal', sa.DECIMAL(precision=20, scale=2), nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.DECIMAL(precision=20, scale=2), nullable=True))
    op.add_column('orders', sa.Column('delivery_fee', sa.DECIMAL(precision=20, scale=2), nullable=True))
    op.add_column('orders', sa.Column('coupon_code', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('gift_message', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_orders_razorpay_payment_id'), 'orders', ['razorpay_payment_id'], unique=False)
    op.add_column('products', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('sub_category_slug', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('sub_category_name', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('age_range', sa.String(length=40), nullable=True))
    op.add_column('products', sa.Column('is_new', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('products', sa.Column('variant_group_id', sa.String(length=64), nullable=True))
    op.add_column('products', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('color_hex', sa.String(length=7), nullable=True))
    op.add_column('products', sa.Column('color_variants', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.add_column('products', sa.Column('product_video', sa.String(length=512), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('products', 'details',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('products', 'original_price',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('products', 'amount_discount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'offer_expiration_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_products_category', table_name='products')
    op.drop_index('ix_products_description', table_name='products')
    op.drop_index('ix_products_id', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_sub_category_slug'), 'products', ['sub_category_slug'], unique=False)
    op.create_index(op.f('ix_products_variant_group_id'), 'products', ['variant_group_id'], unique=False)
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('products', 'date_published')
    op.add_column('ratings', sa.Column('order_id', sa.UUID(), nullable=True))
    op.add_column('ratings', sa.Column('comment', sa.Text(), server_default='', nullable=False))
    op.add_column('ratings', sa.Column('helpful_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('ratings', sa.Column('is_approved', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('ratings', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index('ix_ratings_id', table_name='ratings')
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=True)
    op.create_foreign_key(None, 'ratings', 'orders', ['order_id'], ['id'])
    op.drop_column('ratings', 'review')
    op.add_column('user_addresses', sa.Column('full_name', sa.String(length=255), server_default='', nullable=False))
    op.add_column('user_addresses', sa.Column('phone', sa.String(length=20), server_default='', nullable=False))
    op.add_column('user_addresses', sa.Column('address_type', sa.String(length=20), server_default='home', nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('dob', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'is_active')
    op.drop_column('user_addresses', 'address_type')
    op.drop_column('user_addresses', 'phone')
    op.drop_column('user_addresses', 'full_name')
    op.add_column('ratings', sa.Column('review', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.create_index('ix_ratings_id', 'ratings', ['id'], unique=False)
    op.drop_column('ratings', 'created_at')
    op.drop_column('ratings', 'is_approved')
    op.drop_column('ratings', 'helpful_count')
    op.drop_column('ratings', 'comment')
    op.drop_column('ratings', 'order_id')
    op.add_column('products', sa.Column('date_published', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_variant_group_id'), table_name='products')
    op.drop_index(op.f('ix_products_sub_category_slug'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.create_index('ix_products_description', 'products', ['description'], unique=False)
    op.create_index('ix_products_category', 'products', ['category'], unique=False)
    op.alter_column('products', 'offer_expiration_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('products', 'amount_discount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'original_price',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'details',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('products', 'product_video')
    op.drop_column('products', 'color_variants')
    op.drop_column('products', 'color_hex')
    op.drop_column('products', 'color')
    op.drop_column('products', 'variant_group_id')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'is_featured')
    op.drop_column('products', 'is_new')
    op.drop_column('products', 'age_range')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'sub_category_name')
    op.drop_column('products', 'sub_category_slug')
    op.drop_column('products', 'category_id')
    op.drop_index(op.f('ix_orders_razorpay_payment_id'), table_name='orders')
    op.drop_column('orders', 'gift_message')
    op.drop_column('orders', 'coupon_code')
    op.drop_column('orders', 'delivery_fee')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'razorpay_payment_id')
    op.drop_column('order_items', 'image')
    op.drop_column('order_items', 'color_hex')
    op.drop_column('order_items', 'color')
    op.drop_column('cart_items', 'image')
    op.drop_column('cart_items', 'color_hex')
    op.drop_column('cart_items', 'color')
    # ### end Alembic commands ###
