"""add_tables_never_captured_by_migrations

21 tables (categories, blog_posts, coupons, notifications, payment_orders,
the 6 returns tables, the 6 shipping tables, courier_partners,
newsletter_subscribers, store_settings) exist only as SQLAlchemy models -
no prior migration ever created them. The dev DB never noticed because
app/main.py runs Base.metadata.create_all() unconditionally at import time,
silently patching over the gap. On a genuinely empty database this is fatal:
27482216f0e8 (sync_models_schema_drift) adds a FK from products.category_id
to categories, which doesn't exist yet - alembic upgrade head crashes
outright. Inserted here (before 27482216f0e8, not appended at head) so
`categories` exists in time for that FK.

NOTE on how this file was produced: autogenerated by diffing a DB stamped
(not migrated) to head against the current models, which - as expected -
also picked up every column-level change 27482216f0e8 and later migrations
already make to existing tables (products, cart_items, orders, etc). Those
were manually stripped back out here, keeping only the create_table/
create_index calls for the tables no migration anywhere else touches -
otherwise this migration and 27482216f0e8 would both try to add the same
columns, and a fresh-DB replay would crash on "column already exists" the
moment it reached 27482216f0e8. Verified via a real empty-DB replay of the
full chain after trimming (see backend deployment audit).

Revision ID: 6499c4edd4d2
Revises: 6707115b61f9
Create Date: 2026-07-08 13:24:20.574720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6499c4edd4d2'
down_revision: Union[str, None] = '6707115b61f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('blog_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tag', sa.String(length=80), nullable=True),
    sa.Column('image_url', sa.String(length=600), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('coupons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('min_order', sa.Float(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('courier_partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('service_type', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('supports_cod', sa.Boolean(), nullable=False),
    sa.Column('tracking_url_template', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courier_partners_id'), 'courier_partners', ['id'], unique=False)
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_newsletter_subscribers_id'), 'newsletter_subscribers', ['id'], unique=False)
    op.create_table('store_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('payment_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('cart_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('shipping_address', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_orders_razorpay_order_id'), 'payment_orders', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_payment_orders_razorpay_payment_id'), 'payment_orders', ['razorpay_payment_id'], unique=False)
    op.create_table('return_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_refund_amount', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_requests_id'), 'return_requests', ['id'], unique=False)
    op.create_index(op.f('ix_return_requests_order_id'), 'return_requests', ['order_id'], unique=False)
    op.create_index(op.f('ix_return_requests_status'), 'return_requests', ['status'], unique=False)
    op.create_index(op.f('ix_return_requests_user_id'), 'return_requests', ['user_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('is_prepaid', sa.Boolean(), nullable=False),
    sa.Column('cod_amount', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('cod_collected', sa.Boolean(), nullable=False),
    sa.Column('cod_collected_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cod_remitted', sa.Boolean(), nullable=False),
    sa.Column('cod_remittance_reference', sa.String(length=120), nullable=True),
    sa.Column('cod_remitted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('courier_partner_id', sa.UUID(), nullable=True),
    sa.Column('courier_name', sa.String(length=120), nullable=True),
    sa.Column('courier_service', sa.String(length=120), nullable=True),
    sa.Column('awb_number', sa.String(length=120), nullable=True),
    sa.Column('tracking_url', sa.Text(), nullable=True),
    sa.Column('label_url', sa.Text(), nullable=True),
    sa.Column('label_public_id', sa.String(length=200), nullable=True),
    sa.Column('label_generated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('shipping_cost', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('package_weight', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('package_length', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('package_width', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('package_height', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('ship_name', sa.String(length=200), nullable=True),
    sa.Column('ship_phone', sa.String(length=20), nullable=True),
    sa.Column('ship_line1', sa.String(length=300), nullable=True),
    sa.Column('ship_city', sa.String(length=120), nullable=True),
    sa.Column('ship_state', sa.String(length=120), nullable=True),
    sa.Column('ship_pincode', sa.String(length=12), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('pickup_scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('pickup_attempts', sa.Integer(), nullable=False),
    sa.Column('packed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('rto_initiated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('rto_received_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['courier_partner_id'], ['courier_partners.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_awb_number'), 'shipments', ['awb_number'], unique=False)
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=False)
    op.create_index(op.f('ix_shipments_ship_city'), 'shipments', ['ship_city'], unique=False)
    op.create_index(op.f('ix_shipments_ship_pincode'), 'shipments', ['ship_pincode'], unique=False)
    op.create_index(op.f('ix_shipments_ship_state'), 'shipments', ['ship_state'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_index(op.f('ix_shipments_user_id'), 'shipments', ['user_id'], unique=False)
    op.create_table('delivery_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('failure_reason', sa.String(length=60), nullable=True),
    sa.Column('courier_remarks', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('customer_contacted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_attempts_id'), 'delivery_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_attempts_shipment_id'), 'delivery_attempts', ['shipment_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_request_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gateway_refund_id', sa.String(length=64), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=64), nullable=True),
    sa.Column('gateway_status', sa.String(length=20), nullable=True),
    sa.Column('speed', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_gateway_refund_id'), 'refunds', ['gateway_refund_id'], unique=False)
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=False)
    op.create_index(op.f('ix_refunds_return_request_id'), 'refunds', ['return_request_id'], unique=True)
    op.create_table('replacement_shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_request_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tracking_number', sa.String(length=120), nullable=True),
    sa.Column('dispatched_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replacement_shipments_id'), 'replacement_shipments', ['id'], unique=False)
    op.create_index(op.f('ix_replacement_shipments_return_request_id'), 'replacement_shipments', ['return_request_id'], unique=True)
    op.create_table('return_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_request_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('item_price', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('condition_status', sa.String(length=20), nullable=False),
    sa.Column('restock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_resellable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_items_id'), 'return_items', ['id'], unique=False)
    op.create_index(op.f('ix_return_items_return_request_id'), 'return_items', ['return_request_id'], unique=False)
    op.create_table('return_proofs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_request_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_proofs_id'), 'return_proofs', ['id'], unique=False)
    op.create_index(op.f('ix_return_proofs_return_request_id'), 'return_proofs', ['return_request_id'], unique=False)
    op.create_table('return_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_request_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(length=40), nullable=True),
    sa.Column('new_status', sa.String(length=40), nullable=False),
    sa.Column('changed_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_status_history_id'), 'return_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_return_status_history_return_request_id'), 'return_status_history', ['return_request_id'], unique=False)
    op.create_table('shipment_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition_status', sa.String(length=20), nullable=False),
    sa.Column('restock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_resellable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_items_id'), 'shipment_items', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_items_shipment_id'), 'shipment_items', ['shipment_id'], unique=False)
    op.create_table('shipment_notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('provider_ref', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_notification_logs_id'), 'shipment_notification_logs', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_notification_logs_shipment_id'), 'shipment_notification_logs', ['shipment_id'], unique=False)
    op.create_table('shipment_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(length=40), nullable=True),
    sa.Column('new_status', sa.String(length=40), nullable=False),
    sa.Column('changed_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_status_history_id'), 'shipment_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_status_history_shipment_id'), 'shipment_status_history', ['shipment_id'], unique=False)
    op.create_table('shipping_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('label_url', sa.Text(), nullable=False),
    sa.Column('label_public_id', sa.String(length=200), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('generated_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_labels_id'), 'shipping_labels', ['id'], unique=False)
    op.create_index(op.f('ix_shipping_labels_shipment_id'), 'shipping_labels', ['shipment_id'], unique=False)


def downgrade() -> None:
    op.drop_table('shipping_labels')
    op.drop_table('shipment_status_history')
    op.drop_table('shipment_notification_logs')
    op.drop_table('shipment_items')
    op.drop_table('return_status_history')
    op.drop_table('return_proofs')
    op.drop_table('return_items')
    op.drop_table('replacement_shipments')
    op.drop_table('refunds')
    op.drop_table('delivery_attempts')
    op.drop_table('shipments')
    op.drop_table('return_requests')
    op.drop_table('payment_orders')
    op.drop_table('notifications')
    op.drop_table('store_settings')
    op.drop_table('newsletter_subscribers')
    op.drop_table('courier_partners')
    op.drop_table('coupons')
    op.drop_table('categories')
    op.drop_table('blog_posts')
