"""add_sku_slug_gst_hsn_weight_dimensions_personalisation_seo_to_products

Revision ID: 97fc59b3d306
Revises: 27482216f0e8
Create Date: 2026-07-05 11:29:44.219777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97fc59b3d306'
down_revision: Union[str, None] = '27482216f0e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.String(length=64), nullable=True))
    op.add_column('products', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('gst_percent', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('hsn', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('weight_g', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('dimensions', sa.String(length=60), nullable=True))
    op.add_column('products', sa.Column('personalisation_options', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.add_column('products', sa.Column('seo_title', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('seo_description', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_column('products', 'seo_description')
    op.drop_column('products', 'seo_title')
    op.drop_column('products', 'personalisation_options')
    op.drop_column('products', 'dimensions')
    op.drop_column('products', 'weight_g')
    op.drop_column('products', 'hsn')
    op.drop_column('products', 'gst_percent')
    op.drop_column('products', 'slug')
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###
